inventorization_systems/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', include(('categories.urls',  'categories'), namespace='categories')),
    path('', include(('records.urls', 'records'), namespace='records')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path

from .views import RecordCreateView, RecordsListView, RecordDetailView, SuccessMessageTemplateView
from .views import accept_record, reject_record, close_record

urlpatterns = [
    path(
        '',
        RecordCreateView.as_view(),
        name='create-record'
    ),
    path(
        'ticket/create/',
        RecordCreateView.as_view(),
        name='create-record'
    ),
    path(
        'tickets/',
        RecordsListView.as_view(),
        name='list-records'
    ),
    path(
        'ticket/<int:pk>',
        RecordDetailView.as_view(),
        name='detail-record'
    ),
    path(
        'ticket/<int:pk>/accept/',
        accept_record,
        name='accept-record'
    ),
    path(
        'ticket/<int:pk>/reject/',
        reject_record,
        name='reject-record'
    ),
    path(
        'ticket/<int:pk>/close/',
        close_record,
        name='close-record'
    ),
    path(
        'ticket-success-message/',
        SuccessMessageTemplateView.as_view(),
        name='template-success-message'
    ),
]

records/models.py
from django.db import models
from django.conf import settings

from categories.models import Category
from locations.models import Location


class Record(models.Model):

    name = models.CharField(
        max_length=150
    )

    surname = models.CharField(
        max_length=150
    )

    number = models.CharField(
        max_length=150,
        help_text="+994 xx xxx xx xx"
    )

    location = models.ForeignKey(
        Location,
        null=True,
        on_delete=models.SET_NULL,
        related_name='tickets',
        related_query_name='ticket'
    )

    category = models.ForeignKey(
        Category,
        null=True,
        on_delete=models.SET_NULL,
        related_name='tickets',
        related_query_name='ticket',
    )

    content = models.TextField()

    status = models.CharField(
        max_length=150,
        choices=[
            ("accept", "accepted"),
            ("pend", "pending"),
            ("reject", "rejected"),
            ("close", "closed"),
        ]
    )

    created_at = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return '%s->%s' % (
            self.surname,
            self.number
        )

records/views.py
from django.views import generic
from django.contrib.auth import mixins
from django.urls import reverse_lazy
from django.forms.models import modelform_factory, ModelForm
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404, get_list_or_404

from categories.models import Category
from .models import Record
from bases.models import Navbar, Footer


class RecordCreateView(generic.CreateView):
    model = Record
    template_name = 'records/create/create-record.html'
    success_url = reverse_lazy('records:template-success-message')

    def get_form_class(self):
        return modelform_factory(
            self.model,
            form=ModelForm,
            exclude=[
                "status",
                "created_by",
                "created_at"
            ]
        )

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.status = "pend"
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context['navbar'] = Navbar.objects.get(
            type="unauthorized"
        )
        context['footer'] = Footer.objects.get(
            type="unauthorized"
        )
        return context


class RecordsListView(mixins.LoginRequiredMixin, generic.ListView):
    model = Record
    context_object_name = 'records'
    template_name = 'records/list/list-records.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context['categories'] = Category.objects.filter(
            department=self.request.user.department
        )

        context['navbar'] = Navbar.objects.filter(
            type="authorized"
        ).first()

        context['footer'] = Footer.objects.filter(
            type="authorized"
        ).first()

        return context


class SuccessMessageTemplateView(generic.TemplateView):
    template_name = 'records/template/template-success-message.html'


class RecordDetailView(mixins.LoginRequiredMixin, generic.DetailView):
    model = Record
    template_name = 'records/detail/detail-record.html'
    temp_object_name = 'record'


def accept_record(request, pk):
    record = Record.objects.get(pk=pk)
    record.status = "accept"
    record.save()
    return redirect('records:list-records')


def reject_record(request, pk):
    record = Record.objects.get(pk=pk)
    record.status = "reject"
    record.save()
    return redirect('records:list-records')


def close_record(request, pk):
    record = Record.objects.get(pk=pk)
    record.status = "close"
    record.save()
    return redirect('records:list-records')

records/templates/records/detail/detail-record.html
{% extends 'bases/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    Detail Ticket
{% endblock %}

{% block breadcrumb %}
    <div class="row mb-1 mx-0 justify-content-end">
        <a href="{% url 'records:list-records' %}" class="btn btn-outline-primary mx-0" style="box-shadow: none!important; background-color: transparent;">
            View Records
        </a>
    </div>
{% endblock %}

{% block main %}


    <div class="row bg-white">

        <div class="col-12 p-5 rounded">

            <div id="div_id_name" class="form-group">
                <label for="id_name" class=" requiredField">
                    Name
                    <span class="asteriskField">*</span>
                </label>
                <div class="">
                    <input type="text" name="name" value="{{ record.name }}"maxlength="150" class="textinput textInput form-control disabled" required id="id_name">
                </div>
            </div>
            <div id="div_id_surname" class="form-group">
                <label for="id_surname" class=" requiredField">
                    Surname
                    <span class="asteriskField">*</span>
                </label>
                <div class="">
                    <input type="text" name="surname" value="{{ record.surname }}" maxlength="150" class="textinput textInput form-control disabled" required id="id_surname">
                </div>
            </div>
            <div id="div_id_number" class="form-group">
                <label for="id_number" class=" requiredField">
                    Number
                    <span class="asteriskField">*</span>
                </label>
                <div class="">
                    <input type="text" name="number" value="{{ record.number }}" maxlength="150" class="textinput textInput form-control disabled" required id="id_number">
                    <small id="hint_id_number" class="form-text text-muted">+994 xx xxx xx xx</small>
                </div>
            </div>
            <div id="div_id_content" class="form-group"> <label for="id_content" class=" requiredField">
                Content
                <span class="asteriskField">*</span>
            </label>
                <div class="">
                    <textarea name="content" cols="40" rows="10" class="textarea form-control disabled" required id="id_content">{{ record.content }}</textarea>
                </div>
            </div>
            <div id="div_id_status" class="form-group">
                <label for="id_status" class=" requiredField">
                    Surname
                    <span class="asteriskField">*</span>
                </label>
                <div class="">
                    <input type="text" name="status" value="{{ record.get_status_display }}" maxlength="150" class="textinput textInput form-control disabled" required id="id_status">
                </div>
            </div>


        </div>

    </div>

{% endblock %}