inventorization_systems/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', include(('categories.urls',  'categories'), namespace='categories')),
    path('', include(('records.urls', 'records'), namespace='records')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path

from .views import RecordCreateView, RecordsListView, RecordDetailView, SuccessMessageTemplateView
from .views import accept_record, reject_record, close_record

urlpatterns = [
    path(
        '',
        RecordCreateView.as_view(),
        name='create-record'
    ),
    path(
        'ticket/create/',
        RecordCreateView.as_view(),
        name='create-record'
    ),
    path(
        'tickets/',
        RecordsListView.as_view(),
        name='list-records'
    ),
    path(
        'ticket/<int:pk>',
        RecordDetailView.as_view(),
        name='detail-record'
    ),
    path(
        'ticket/<int:pk>/accept/',
        accept_record,
        name='accept-record'
    ),
    path(
        'ticket/<int:pk>/reject/',
        reject_record,
        name='reject-record'
    ),
    path(
        'ticket/<int:pk>/close/',
        close_record,
        name='close-record'
    ),
    path(
        'ticket-success-message/',
        SuccessMessageTemplateView.as_view(),
        name='template-success-message'
    ),
]

records/models.py
from django.db import models
from django.conf import settings

from categories.models import Category
from locations.models import Location


class Record(models.Model):

    name = models.CharField(
        max_length=150
    )

    surname = models.CharField(
        max_length=150
    )

    number = models.CharField(
        max_length=150,
        help_text="+994 xx xxx xx xx"
    )

    location = models.ForeignKey(
        Location,
        null=True,
        on_delete=models.SET_NULL,
        related_name='tickets',
        related_query_name='ticket'
    )

    category = models.ForeignKey(
        Category,
        null=True,
        on_delete=models.SET_NULL,
        related_name='tickets',
        related_query_name='ticket',
    )

    content = models.TextField()

    status = models.CharField(
        max_length=150,
        choices=[
            ("accept", "accepted"),
            ("pend", "pending"),
            ("reject", "rejected"),
            ("close", "closed"),
        ]
    )

    created_at = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return '%s->%s' % (
            self.surname,
            self.number
        )

records/views.py
from django.views import generic
from django.contrib.auth import mixins
from django.urls import reverse_lazy
from django.forms.models import modelform_factory, ModelForm
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404, get_list_or_404

from categories.models import Category
from .models import Record
from bases.models import Navbar, Footer


class RecordCreateView(generic.CreateView):
    model = Record
    template_name = 'records/create/create-record.html'
    success_url = reverse_lazy('records:template-success-message')

    def get_form_class(self):
        return modelform_factory(
            self.model,
            form=ModelForm,
            exclude=[
                "status",
                "created_by",
                "created_at"
            ]
        )

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.status = "pend"
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context['navbar'] = Navbar.objects.get(
            type="unauthorized"
        )
        context['footer'] = Footer.objects.get(
            type="unauthorized"
        )
        return context


class RecordsListView(mixins.LoginRequiredMixin, generic.ListView):
    model = Record
    context_object_name = 'records'
    template_name = 'records/list/list-records.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context['categories'] = Category.objects.filter(
            department=self.request.user.department
        )

        context['navbar'] = Navbar.objects.filter(
            type="authorized"
        ).first()

        context['footer'] = Footer.objects.filter(
            type="authorized"
        ).first()

        return context


class SuccessMessageTemplateView(generic.TemplateView):
    template_name = 'records/template/template-success-message.html'


class RecordDetailView(mixins.LoginRequiredMixin, generic.DetailView):
    model = Record
    template_name = 'records/detail/detail-record.html'
    temp_object_name = 'record'


def accept_record(request, pk):
    record = Record.objects.get(pk=pk)
    record.status = "accept"
    record.save()
    return redirect('records:list-records')


def reject_record(request, pk):
    record = Record.objects.get(pk=pk)
    record.status = "reject"
    record.save()
    return redirect('records:list-records')


def close_record(request, pk):
    record = Record.objects.get(pk=pk)
    record.status = "close"
    record.save()
    return redirect('records:list-records')

records/templates/records/list/list-records.html
{% extends 'bases/base.html' %}

{% load static %}

{% block title %}
    Records
{% endblock %}

{% block breadcrumb %}
    {#    <nav aria-label="breadcrumb">#}
    {#        <ol class="breadcrumb mb-0 px-0" style="background-color: transparent!important;">#}
    {#            <li class="breadcrumb-item"><a href="{% url "categories:list-categories" %}">categories</a></li>#}
    {#            <li class="breadcrumb-item"><a href="{% url "elements:list-elements" records.0.group.element.name %}">elements</a></li>#}
    {#            <li class="breadcrumb-item"><a href="{% url "groups:list-groups" records.0.group.element.category.name records.0.group.element.name %}">groups</a></li>#}
    {#            <li class="breadcrumb-item active">records</li>#}
    {#        </ol>#}
    {#    </nav>#}
{% endblock %}


{% block main %}
    {% if records %}
        {#        <div class="row mb-1 mx-0 justify-content-end">#}
        {#            <a href="{% url 'records:create-computer' records.0.group.element.category.name|lower records.0.group.element.name|lower records.0.group.name|lower %}" class="btn btn-outline-primary" style="box-shadow: none!important; background-color: transparent;">#}
        {#                <i class="fas fa-plus" aria-hidden="true"></i>#}
        {#                add new record#}
        {#            </a>#}
        {#        </div>#}

        <div class="row mb-5 mx-0">

            <div class="col p-2 border rounded bg-white">


                <table id="table" class="display table-bordered compact w-100 mx-0 animated fadeIn delay-1s">
                    <thead>
                    <tr>
                        <th>name</th>
                        <th>surname</th>
                        <th>number</th>
                        <th>location</th>
                        <th>category</th>
                        <th>status</th>
                        <th>when</th>
                        <th>action</th>
                    </tr>

                    </thead>

                    <tbody>
                    {% for record in records %}
                        <tr>
                            <td class="dt-size">{{ record.name}}</td>
                            <td class="dt-size">{{ record.surname}}</td>
                            <td class="dt-size">{{ record.number}}</td>
                            <td class="dt-size">{{ record.location.name}}</td>
                            <td class="dt-size">{{ record.category.name}}</td>
                            <td class="dt-size">{{ record.get_status_display}}</td>
                            <td class="dt-size">{{ record.created_at|date:"D d M Y H:i" }}</td>
                            <td class="dt-size text-center">
                                <a href="{% url 'records:detail-record' record.pk %}"><i class="far fa-eye mr-2"></i></a>

                                {% if not record.status == 'close' %}

                                    {% if not record.status == 'accept' %}
                                        <a href="{% url 'records:accept-record' record.pk %}"><i class="fas fa-plus mr-2"></i></a>
                                    {% endif %}

                                    {% if not record.status == 'reject' %}
                                        <a href="{% url 'records:reject-record' record.pk %}"><i class="fas fa-times mr-2"></i></a>
                                    {% endif %}

                                    <a href="{% url 'records:close-record' record.pk %}"><i class="far fa-window-close"></i></a>

                                {% else %}

                                    ticket closed

                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>

            </div>

        </div>
    {% else %}
        <div class="row p-5 justify-content-center">
            {{ 'no records' |capfirst }}
        </div>
    {% endif %}
{% endblock %}